class_name AudioBuses
extends RefCounted
## The 03 §3 bus tree and its effects, built in code so the layout file
## (game/default_bus_layout.tres, generated by tools/audio/make_bus_layout.gd) and a
## missing or stale layout both end in the same mix.
##
## Master (limiter -1 dBFS)
## ├── World (reverb per stratum; high-pass for the Substrate's empty render)
## │   ├── Footsteps, Interact, Errors (limiter -6 dBFS, rule 2), Ambience
## ├── Player (low shelf +2 dB at 90 Hz)
## ├── Music
## └── UI

## bus -> parent, in AudioServer index order (Tuning.AUDIO_BUSES).
const PARENT: Dictionary = {
	&"World": &"Master", &"Footsteps": &"World", &"Interact": &"World", &"Errors": &"World",
	&"Ambience": &"World", &"Player": &"Master", &"Music": &"Master", &"UI": &"Master",
}

## Effect slots on their buses.
const WORLD_REVERB := 0
const WORLD_HIGHPASS := 1
const MASTER_LIMITER := 0
const ERRORS_LIMITER := 0
const PLAYER_SHELF := 0


## True when every bus exists in order, routed and carrying its effects.
static func is_complete() -> bool:
	for i in Tuning.AUDIO_BUSES.size():
		var bus: StringName = Tuning.AUDIO_BUSES[i]
		if AudioServer.get_bus_index(bus) != i:
			return false
		if PARENT.has(bus) and AudioServer.get_bus_send(i) != PARENT[bus]:
			return false
	return reverb() != null and highpass() != null \
		and _effect(&"Master", MASTER_LIMITER) is AudioEffectHardLimiter \
		and _effect(&"Errors", ERRORS_LIMITER) is AudioEffectHardLimiter \
		and _effect(&"Player", PLAYER_SHELF) is AudioEffectLowShelfFilter


## Rebuilds the whole layout when anything is missing. Safe to call repeatedly.
static func ensure() -> void:
	if is_complete():
		return
	AudioServer.bus_count = Tuning.AUDIO_BUSES.size()
	for i in Tuning.AUDIO_BUSES.size():
		var bus: StringName = Tuning.AUDIO_BUSES[i]
		AudioServer.set_bus_name(i, bus)
		AudioServer.set_bus_volume_db(i, 0.0)
		AudioServer.set_bus_mute(i, false)
		AudioServer.set_bus_solo(i, false)
		AudioServer.set_bus_bypass_effects(i, false)
		while AudioServer.get_bus_effect_count(i) > 0:
			AudioServer.remove_bus_effect(i, 0)
		if PARENT.has(bus):
			AudioServer.set_bus_send(i, PARENT[bus])
	var limiter := AudioEffectHardLimiter.new()
	limiter.ceiling_db = Tuning.AUDIO_LIMITER_CEILING_DB
	AudioServer.add_bus_effect(AudioServer.get_bus_index(&"Master"), limiter)
	var world := AudioServer.get_bus_index(&"World")
	var reverb_fx := AudioEffectReverb.new()
	reverb_fx.dry = 1.0
	_apply_reverb(reverb_fx, Tuning.AUDIO_REVERB[&"halls"])
	AudioServer.add_bus_effect(world, reverb_fx)
	var hp := AudioEffectHighPassFilter.new()
	hp.cutoff_hz = 300.0
	AudioServer.add_bus_effect(world, hp)
	AudioServer.set_bus_effect_enabled(world, WORLD_HIGHPASS, false)
	var errors_limiter := AudioEffectHardLimiter.new()
	errors_limiter.ceiling_db = Tuning.AUDIO_ERRORS_BUS_MAX_DB  # 03 §6 rule 2
	AudioServer.add_bus_effect(AudioServer.get_bus_index(&"Errors"), errors_limiter)
	var shelf := AudioEffectLowShelfFilter.new()
	shelf.cutoff_hz = Tuning.AUDIO_PLAYER_LOW_SHELF_HZ
	shelf.gain = db_to_linear(Tuning.AUDIO_PLAYER_LOW_SHELF_DB)
	AudioServer.add_bus_effect(AudioServer.get_bus_index(&"Player"), shelf)


static func reverb() -> AudioEffectReverb:
	return _effect(&"World", WORLD_REVERB) as AudioEffectReverb


static func highpass() -> AudioEffectHighPassFilter:
	return _effect(&"World", WORLD_HIGHPASS) as AudioEffectHighPassFilter


## Reverb parameters for a stratum: the StratumData resource first (data/strata), then
## Tuning.AUDIO_REVERB. Keys: room, damping, wet, predelay_ms, highpass_hz.
static func reverb_params(stratum: StringName) -> Dictionary:
	var data := DataRegistry.stratum(stratum)
	if data != null:
		return {
			&"room": data.reverb_room_size, &"damping": data.reverb_damping, &"wet": data.reverb_wet,
			&"predelay_ms": data.reverb_predelay_ms, &"highpass_hz": data.reverb_highpass_hz,
		}
	var t: Dictionary = Tuning.AUDIO_REVERB.get(stratum, Tuning.AUDIO_REVERB[&"halls"])
	return {
		&"room": float(t.get(&"room", 0.5)), &"damping": float(t.get(&"damping", 0.5)),
		&"wet": float(t.get(&"wet", 0.2)), &"predelay_ms": float(t.get(&"predelay_ms", 0.0)),
		&"highpass_hz": float(t.get(&"highpass_hz", 0.0)),
	}


## The live reverb as the same dictionary shape.
static func current_reverb() -> Dictionary:
	var r := reverb()
	if r == null:
		return {}
	var hp := highpass()
	var world := AudioServer.get_bus_index(&"World")
	var hp_on := hp != null and AudioServer.is_bus_effect_enabled(world, WORLD_HIGHPASS)
	return {
		&"room": r.room_size, &"damping": r.damping, &"wet": r.wet, &"predelay_ms": r.predelay_msec,
		&"highpass_hz": hp.cutoff_hz if hp_on else 0.0,
	}


## Sets the reverb to the blend `t` (0..1) between two parameter sets (the 1 s crossfade).
static func blend_reverb(from: Dictionary, to: Dictionary, t: float) -> void:
	var r := reverb()
	if r == null:
		return
	var mixed := {}
	for k: StringName in [&"room", &"damping", &"wet", &"predelay_ms"]:
		mixed[k] = lerpf(float(from.get(k, 0.0)), float(to.get(k, 0.0)), t)
	_apply_reverb(r, mixed)
	# 03 §3: the Substrate's 300 Hz high-pass switches with the target, not blended.
	var hp_hz := float(to.get(&"highpass_hz", 0.0))
	var world := AudioServer.get_bus_index(&"World")
	if highpass() != null:
		AudioServer.set_bus_effect_enabled(world, WORLD_HIGHPASS, hp_hz > 0.0)
		if hp_hz > 0.0:
			highpass().cutoff_hz = hp_hz


static func _apply_reverb(r: AudioEffectReverb, p: Dictionary) -> void:
	r.room_size = clampf(float(p.get(&"room", 0.5)), 0.0, 1.0)
	r.damping = clampf(float(p.get(&"damping", 0.5)), 0.0, 1.0)
	r.wet = clampf(float(p.get(&"wet", 0.2)), 0.0, 1.0)
	# Godot's reverb pre-delay floor is 20 ms; strata without one use the floor.
	r.predelay_msec = clampf(float(p.get(&"predelay_ms", 0.0)), 20.0, 500.0)
	r.predelay_feedback = 0.0


static func _effect(bus: StringName, slot: int) -> AudioEffect:
	var i := AudioServer.get_bus_index(bus)
	if i < 0 or slot >= AudioServer.get_bus_effect_count(i):
		return null
	return AudioServer.get_bus_effect(i, slot)
